### ISSUE TITLE
Greate work progress Mohamed

### ISSUE THREAD

**Issue by CalyCherkaoui** [mohamedSabry0/ruLint#2]
Good job Mohamed! We know that linter is not an easy project. :)
If you want some improvement you could refactor a little bit your classes:
- Instead of declaring a Naming class that inherits from Parser, you may include it as a public method in the parser or having a module for it.
- Also, in the Parser class, the line_parser method is returning the same result as the @file variable (lines 14 to 21).

**Comment by mohamedSabry0** [comment]
Thank you for your review.
